GOOGLE_MAPS_API_URL: "https://maps.googleapis.com/maps/api/distancematrix/json?avoid=tolls&avoid=highways"
GOOGLE_MAPS_GEOCODE: "https://maps.googleapis.com/maps/api/geocode/json"
CONFIGURABLE_MINIMUM_JOBS_FOR_RIDER: "1"
CONFIGURABLE_MINIMUM_RIDERS_FOR_JOB: "1" 
CONFIGURABLE_MAXIMUM_JOBS_FOR_RIDER: "10"
CONFIGURABLE_MAXIMUM_RIDERS_FOR_JOB: "100"
NO_OF_PARTITIONS: "5"
RIDER_SERVICE: "http://rider-service.preprod:8080"
COGNITO_URL_APP: https://cognito-idp.ap-southeast-1.amazonaws.com/ap-southeast-1_Bt3MWkPyC
COGNITO_URL_OPS: https://cognito-idp.ap-southeast-1.amazonaws.com/ap-southeast-1_sGv2dsTck