GOOGLE_MAPS_API_URL: "http://10.254.246.36:8081/maps/api/distancematrix/json"
GOOGLE_MAPS_GEOCODE: "http://10.254.246.36:8081/maps/api/geocode/json"
CONFIGURABLE_MINIMUM_JOBS_FOR_RIDER: "1"
CONFIGURABLE_MINIMUM_RIDERS_FOR_JOB: "1" 
CONFIGURABLE_MAXIMUM_JOBS_FOR_RIDER: "10"
CONFIGURABLE_MAXIMUM_RIDERS_FOR_JOB: "100"
NO_OF_PARTITIONS: "200"
RIDER_SERVICE: "http://rider-service.preprod3:8080"
COGNITO_URL_APP: https://cognito-idp.ap-southeast-1.amazonaws.com/ap-southeast-1_o70Wdkbyc
COGNITO_URL_OPS: https://cognito-idp.ap-southeast-1.amazonaws.com/ap-southeast-1_bn9ChdPT1
